#!/bin/sh

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer
chmod -R 755 /var/www/html/storage
chmod -R 755 /var/www/html/bootstrap/cache

# Iniciar supervisor (que gerenciará PHP-FPM e Nginx)
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf